### ISSUE TITLE
Is there $MFT like file in APFS 

### ISSUE THREAD

**Issue by siftuser** [libyal/libfsapfs#21]
What do you use to build the dir structure in APFS ? Is there a physical file like $MFT in APFS

**Comment by joachimmetz** [comment]
Short answer is no. APFS has no file system metadata files. There is a file hierarchy B-tree that is used for similar purposes: https://github.com/libyal/libfsapfs/blob/master/documentation/Apple%20File%20System%20(APFS).asciidoc#10-file-system

If you're looking for sources to read up on https://forensicswiki.xyz/wiki/index.php?title=Apple_File_System_(APFS)

**Comment by siftuser** [comment]
Thank you @joachimmetz 

Is b-tree an independent file like structure in itself or they are attributes stored along with the file or block ?

Curious, how do you or similar tools build dir structure of  a vol ? 

Thanks again

**Comment by joachimmetz** [comment]
> Is b-tree an independent file like structure in itself or they are attributes stored along with the file or block ?

No, it is not a file-like structure. It's part of the file system metadata.

> Curious, how do you or similar tools build dir structure of a vol ?

No sure what you are asking me.

**Comment by siftuser** [comment]
Thanks again @joachimmetz 

> > Curious, how do you or similar tools build dir structure of a vol ?
> 
> No sure what you are asking me.

What I meant was, given a dmg file of an apfs container/volume - how does `fsapfsmount` or other forensic tools populate/derive the directory structure contained in the volume ? As in NTFS it uses $MFT & in HFS+ availability of catalog file etc. For which you mentioned `APFS has no file system metadata files`.  So the question is, `file hierarchy B-tree` you suggested earlier, is it stored as an attribute for each block or an independent data structure ? that is used to build the file/folder hierarchy for a given apfs volume  

thanks

**Comment by joachimmetz** [comment]
> What I meant was, given a dmg file of an apfs container/volume - how does fsapfsmount or other forensic tools populate/derive the directory structure contained in the volume ? 

By reading the file system hierarchy B-Tree, this is similar to a Catalog file, with the exception that it is not a file in the file system sense.

> APFS has no file system metadata files

That does not mean it does not have file system metadata

A "file system metadata file" is "file system metadata" wrapped in a regular file, but there is no need for $MFT and catalog file to be a file. The B-Tree is stored as part of the file system, but is not an entity in the file system hierarchy.

>  is it stored as an attribute for each block or an independent data structure ? 

Not sure what you mean with "attribute for each block" (since both attribute and block have multiple meanings in the context of a file system). The B-tree is stored as part of file system.

**Comment by siftuser** [comment]
@joachimmetz thank you for sharing very useful information, at least I could not find anywhere else. 

wondering is it possible that I could collect/extract a specific artifact (like $MFT) from an apfs container/volume that would help depict/build filesystem activity for that disk. In other words possible to collect just 'file system hierarchy B-Tree' ? (other than fsevents) thanks

**Comment by joachimmetz** [comment]
> In other words possible to collect just file system hierarchy B-Tree ? 

In theory yes, one would need to build a tool that extracts this metadata from the volume that contains the file system. In practice this will not give you anything on MacOS, since the OS does not allow you to read from a mount APFS container/volume device.

**Comment by joachimmetz** [comment]
assuming question is answered, closing issue

**Comment by TrumanHW** [comment]
I know what he's asking and wants ... 

He's lost his data ... did a recovery and no longer has the hierarchical info. 
As in ... all his files are in folders separating them by type, which SUCKS. 

I'm sure this is long since resolved for you ... but you'll have infinitely superior luck using 
R-Studio
UFS Explorer
Recovery Explorer
Or having a professional do it (PC3000 is pretty damned good at recovering your hierarchy with the data) ...
